---
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

issues:
    max-per-linter: 0
    max-same-issues: 0

linters:
    disable-all: true
    enable:
        - errcheck
        - ineffassign
        - misspell
        - revive
        - unused
